### ISSUE TITLE
stdin and stdout

### ISSUE THREAD

**Issue by grylem** [sgerwk/jpegtopdf#1]
Hi
please add support for stdin and stdout like other netpbm utilities. It's very convenient in case of this one
pngtopnm | pnmtojpeg | jpegtopdf
Thanks.

**Comment by sgerwk** [comment]
sounds like a great idea: - is for stdin or stdout

fixed in https://github.com/sgerwk/jpegtopdf/commit/68589eb9a0c761e8a2fbe2ff247faba59537379f and https://github.com/sgerwk/jpegtopdf/commit/b2c66f408b343a1538e7c1e9c086d48776979191
